[files]
extend-exclude = [
    "crates/logic/src/models/l18n/swedish.rs",
    "crates/logic/src/models/l18n/snapshots/invoice_typst_logic__models__l18n__localization__tests__l18n_swedish.snap",
]

[default.extend-words]
Ture = "Ture"
typ = "typ"
