[package]
name = "invoice-typst-render"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal dependencies
invoice-typst-logic.workspace = true

# External dependencies
chrono.workspace = true
typst = "0.13.1"
typst-kit = "0.13.1"
typst-pdf = "0.13.1"
log.workspace = true
serde_json.workspace = true
typed-builder.workspace = true
getset.workspace = true
