[package]
name = "invoice-typst-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal dependencies
invoice-typst-logic.workspace = true
invoice-typst-render.workspace = true

# External dependencies
clap = { version = "4.5.39", features = ["derive"] }
log.workspace = true
thiserror.workspace = true
