[package]
name = "invoice"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal dependencies
invoice-typst-logic.workspace = true
invoice-typst-render.workspace = true

# External dependencies
chrono.workspace = true
colored = "3.0.0"
derive_more.workspace = true
fern = "0.7.1"
clap = { version = "4.5.39", features = ["derive"] }
log.workspace = true
thiserror.workspace = true
