name: Release

on:
    push:
        branches:
            - main

env:
    CARGO_TERM_COLOR: always
    RUST_TOOLCHAIN: 1.85.0

jobs:
    spelling:
        name: Spell Check with Typos
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Actions Repository
              uses: actions/checkout@v4
            - name: Spell Check Repo
              uses: crate-ci/typos@v1.33.1

    check-formatting:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Rust Toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ env.RUST_TOOLCHAIN }}
                  default: true
                  components: rustfmt
            - name: Check formatting
              run: cargo fmt --check

    test-rust:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Rust Toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ env.RUST_TOOLCHAIN }}
                  default: true
            - name: Run rust tests
              run: cargo test --locked -- --test-threads=1

    release:
        needs: [spelling, check-formatting, test-rust]
        runs-on: ubuntu-latest

        permissions:
            contents: write
            id-token: write

        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # required by cargo-release to get tags
            - name: Set up Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ env.RUST_TOOLCHAIN }}
                  default: true
            - name: Install cargo-release
              run: cargo install cargo-release

            - name: Configure Git identity
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

            - name: Run cargo release patch
              env:
                  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
              run: cargo release patch --execute --no-confirm
